cmake_minimum_required(VERSION 3.21)

if (NOT GAME)
	message("From source directory: cmake -DGAME=<game> -P BuildDependencies.cmake")
	return()
endif()

execute_process(COMMAND ${CMAKE_COMMAND} --preset ${GAME} .)
execute_process(COMMAND ${CMAKE_COMMAND} --build --preset ${GAME}-libprotobuf -j10)
execute_process(COMMAND ${CMAKE_COMMAND} --preset ${GAME} .)
execute_process(COMMAND ${CMAKE_COMMAND} --build --preset ${GAME}-libSDL2 -j10)
execute_process(COMMAND ${CMAKE_COMMAND} --preset ${GAME} .)
execute_process(COMMAND ${CMAKE_COMMAND} --build --preset ${GAME}-libSDL2_image -j10)
execute_process(COMMAND ${CMAKE_COMMAND} --preset ${GAME} .)
execute_process(COMMAND ${CMAKE_COMMAND} --build --preset ${GAME}-libSDL2_ttf -j10)
execute_process(COMMAND ${CMAKE_COMMAND} --preset ${GAME} .)
execute_process(COMMAND ${CMAKE_COMMAND} --build --preset ${GAME}-libgtest -j10)
execute_process(COMMAND ${CMAKE_COMMAND} --preset ${GAME} .)
