#ifndef M2_GAMES_LAUNCHER_CFG_H
#define M2_GAMES_LAUNCHER_CFG_H

#include "../../Cfg.h"

typedef enum _CfgLauncherUIButtonType {
	CFG_LAUNCHER_UI_BUTTON_TYPE_ARPG = CFG_UI_BUTTON_TYPE_N,
	CFG_LAUNCHER_UI_BUTTON_TYPE_RTS
} CfgLauncherUIButtonType;

extern const CfgUI CFG_UI_LAUNCHER_ENTRYPOINT;

#endif //M2_GAMES_LAUNCHER_CFG_H
