#ifndef M2_GAMES_LAUNCHER_CFG_H
#define M2_GAMES_LAUNCHER_CFG_H

#include "../../Cfg.h"

typedef enum _LauncherCfgUIButtonType {
	LAUNCHER_CFG_UI_BUTTONTYP_ARPG = CFG_UI_BUTTONTYP_N,
	LAUNCHER_CFG_UI_BUTTONTYP_RTS
} LauncherCfgUIButtonType;

extern const CfgUI LAUNCHER_CFG_UI_ENTRYPOINT;

#endif //M2_GAMES_LAUNCHER_CFG_H
