#include "../Cfg.h"

const CfgCharacter CFG_CHARACTER_PLAYER = {
	.mainTexture = &CFG_OBJTXTR_PLAYER_LOOKDOWN_00,
	.objType = CFG_OBJTYP_PLAYER,
	.walkSpeed = 0.8f,
	.maxHp = 100.0f,
	.defaultRangedWeapon = &CFG_RANGEDWPN_GUN,
	.defaultMeleeWeapon = &CFG_MELEEWPN_BAT,
	.defaultExplosiveWeapon = &CFG_EXPLOSIVEWPN_GRENADE,
	.defaultExplosiveCount = 4,
	.textures = {
		&CFG_OBJTXTR_PLAYER_LOOKDOWN_00, // CFG_CHARTEXTURETYP_LOOKDOWN_00
		&CFG_OBJTXTR_PLAYER_LOOKDOWN_01, // CFG_CHARTEXTURETYP_LOOKDOWN_01
		&CFG_OBJTXTR_PLAYER_LOOKDOWN_02, // CFG_CHARTEXTURETYP_LOOKDOWN_02
		&CFG_OBJTXTR_PLAYER_LOOKLEFT_00, // CFG_CHARTEXTURETYP_LOOKLEFT_00
		&CFG_OBJTXTR_PLAYER_LOOKLEFT_01, // CFG_CHARTEXTURETYP_LOOKLEFT_01
		&CFG_OBJTXTR_PLAYER_LOOKLEFT_02, // CFG_CHARTEXTURETYP_LOOKLEFT_02
		&CFG_OBJTXTR_PLAYER_LOOKRIGHT_00, // CFG_CHARTEXTURETYP_LOOKRIGHT_00
		&CFG_OBJTXTR_PLAYER_LOOKRIGHT_01, // CFG_CHARTEXTURETYP_LOOKRIGHT_01
		&CFG_OBJTXTR_PLAYER_LOOKRIGHT_02, // CFG_CHARTEXTURETYP_LOOKRIGHT_02
		&CFG_OBJTXTR_PLAYER_LOOKUP_00, // CFG_CHARTEXTURETYP_LOOKUP_00
		&CFG_OBJTXTR_PLAYER_LOOKUP_01, // CFG_CHARTEXTURETYP_LOOKUP_01
		&CFG_OBJTXTR_PLAYER_LOOKUP_02, // CFG_CHARTEXTURETYP_LOOKUP_02
	}
};
const CfgCharacter CFG_CHARACTER_SKELETON000 = {
	.mainTexture = &CFG_OBJTXTR_ENEMY_LOOKDOWN_00,
	.objType = CFG_OBJTYP_ENEMY,
	.walkSpeed = 0.55f,
	.maxHp = 100.0f,
	.defaultRangedWeapon = NULL,
	.defaultMeleeWeapon = &CFG_MELEEWPN_SWORD,
	.defaultExplosiveWeapon = NULL,
	.defaultExplosiveCount = 0,
	.textures = {
		&CFG_OBJTXTR_ENEMY_LOOKDOWN_00, // CFG_CHARTEXTURETYP_LOOKDOWN_00
		&CFG_OBJTXTR_ENEMY_LOOKDOWN_01, // CFG_CHARTEXTURETYP_LOOKDOWN_01
		&CFG_OBJTXTR_ENEMY_LOOKDOWN_02, // CFG_CHARTEXTURETYP_LOOKDOWN_02
		&CFG_OBJTXTR_ENEMY_LOOKLEFT_00, // CFG_CHARTEXTURETYP_LOOKLEFT_00
		&CFG_OBJTXTR_ENEMY_LOOKLEFT_01, // CFG_CHARTEXTURETYP_LOOKLEFT_01
		&CFG_OBJTXTR_ENEMY_LOOKLEFT_02, // CFG_CHARTEXTURETYP_LOOKLEFT_02
		&CFG_OBJTXTR_ENEMY_LOOKRIGHT_00, // CFG_CHARTEXTURETYP_LOOKRIGHT_00
		&CFG_OBJTXTR_ENEMY_LOOKRIGHT_01, // CFG_CHARTEXTURETYP_LOOKRIGHT_01
		&CFG_OBJTXTR_ENEMY_LOOKRIGHT_02, // CFG_CHARTEXTURETYP_LOOKRIGHT_02
		&CFG_OBJTXTR_ENEMY_LOOKUP_00, // CFG_CHARTEXTURETYP_LOOKUP_00
		&CFG_OBJTXTR_ENEMY_LOOKUP_01, // CFG_CHARTEXTURETYP_LOOKUP_01
		&CFG_OBJTXTR_ENEMY_LOOKUP_02, // CFG_CHARTEXTURETYP_LOOKUP_02
	}
};
