#ifndef IMPL_LEVELBLUEPRINT_H
#define IMPL_LEVELBLUEPRINT_H

namespace lvl {
	enum ObjectGroup : m2::GroupTypeId {
		NO_GROUP [[maybe_unused]] = 0,
		CONSUMABLE_RESOURCE_GROUP,
		CONSUMABLE_RESOURCE_GROUP_HP,
		CONSUMABLE_RESOURCE_GROUP_N
	};
}

#endif //IMPL_LEVELBLUEPRINT_H
